In [1]:
from sklearn.datasets import load_breast_cancer, load_digits
import numpy as np
from matplotlib import pyplot as plt
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.model_selection import train_test_split

In [2]:
class BernoulliNB:
    pass

In [6]:
np.array([True, True]).dot(np.array([True, True]) + 0)

2

In [11]:
v = np.array([1, 1, 1])
w = np.array(range(9)).reshape(3, 3)

In [13]:
v.dot(w)

array([ 9, 12, 15])

In [14]:
w.dot(v)

array([ 3, 12, 21])

In [15]:
w

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
v == np.array([3, 1])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False