In [291]:
from torch.autograd import Variable
from torch.optim import SGD
from torch import Tensor, ones, rand_like, cat, matmul, add, sub, nn
import math

## Linear Algebra

In [118]:
xT = Tensor([[1, 1, 1, 1, 1], [0, 2, 4, 6, 8]])
x = xT.transpose(0, 1)
b = Tensor([3, -0.4])
y0 = matmul(x, b)
y = add(y0, 0.2*rand_like(y0))
print(x)
print(y)

tensor([[1., 0.],
        [1., 2.],
        [1., 4.],
        [1., 6.],
        [1., 8.]])
tensor([ 3.0958,  2.2656,  1.5475,  0.7787, -0.0077])


In [312]:
bhat = (xT @ x).inverse() @ xT @ y
yhat = matmul(x, bhat)
print(bhat)

tensor([ 3.0748, -0.3847])


In [120]:
e = sub(yhat, y)
print(e.dot(e)/5)
loss = nn.MSELoss()
print(loss(yhat, y))

tensor(0.0005)
tensor(0.0005)


## Gradient Descent

In [178]:
loss = nn.MSELoss()

In [309]:
B0 = Tensor([2, -0.5])
B = Variable(B0,requires_grad=True)
for i in range(300):
    L = loss(X @ B, y)
    L.backward()
#     print(B)
    B = Variable(sub(B, 0.04*B.grad), requires_grad=True)

print(B)
print(bhat)

tensor([ 3.0692, -0.3853], requires_grad=True)
tensor([ 3.0748, -0.3847])


In [307]:
B = Variable(B0,requires_grad=True)
print(B)
L = loss(X @ B, y)
optimizer = SGD([B], lr = 0.008)
print(optimizer.state)
optimizer.step()
optimizer.state

tensor([ 2.0000, -0.5000], requires_grad=True)
defaultdict(<class 'dict'>, {})


defaultdict(dict, {})

In [306]:
def gradient(x, y):
    xt = x.transpose(0, 1)
    n = x.size(0)
    def F(b):
        return 2/n*matmul(xt, sub(x@b, y))
    return F

def gradient2(x, y):
    n = x.size(0)
    def F(b):
        u = sum([b[0] + b[1]*x[i,1] - y[i] for i in range(n)])*2/n
        v = sum([(b[0] + b[1]*x[i,1] - y[i])*x[i,1] for i in range(n)])*2/n
        return Tensor([u, v])
    return F
    

In [214]:
G = gradient(x, y)
G2 = gradient2(x, y)
print(G(b))
print(G2(b))

tensor([ -3.0720, -14.1327])
tensor([ -3.0720, -14.1327])


In [205]:
sum([b[0] + b[1]*x[i,1] - y[i] for i in range(5)])*2/5

tensor(-3.0720)

In [208]:
sum([(b[0] + b[1]*x[i,1] - y[i])*x[i,1] for i in range(5)])*2/5

tensor(-14.1327)

In [184]:
b = Tensor([2, -0.5])

In [185]:
gradient(x, y)(b)

TypeError: 'NoneType' object is not callable

In [220]:
xTx = matmul(xT, x)

In [222]:
xTx.eig()

(tensor([[  1.6210,   0.0000],
         [123.3790,   0.0000]]), tensor([]))

In [304]:
print(L.item())

2.4660627841949463


ValueError: only one element tensors can be converted to Python scalars