In [1]:
from torch.autograd import Variable
from torch import Tensor, ones, rand_like, cat, matmul, add, sub, nn

In [26]:
x = Variable(Tensor([2]), requires_grad=True)

alpha = 0.4
for i in range(7):
    y = matmul(x, x)
    y.backward()
    dx = x.grad.data
    x = Variable(x.data - alpha*x.grad.data, requires_grad=True)
    print(x)

tensor([0.4000], requires_grad=True)
tensor([0.0800], requires_grad=True)
tensor([0.0160], requires_grad=True)
tensor([0.0032], requires_grad=True)
tensor([0.0006], requires_grad=True)
tensor([0.0001], requires_grad=True)
tensor([2.5600e-05], requires_grad=True)
