In [188]:
from torch.autograd import Variable
from torch import Tensor, DoubleTensor
import torch
import math

torch.set_printoptions(precision=16)

In [189]:
x = Variable(torch.Tensor([0]),requires_grad=True)
y = Variable(torch.Tensor([0]),requires_grad=True)
z = 5*x**4 + 3*x**3 -2*y**3 + 7*x**2 + 9*x - 7*y - 5
print(x)
print(x.data)
z.backward()
print(x.grad) # dz/dx
print(y.grad) # dz/dy

tensor([0.], requires_grad=True)
tensor([0.])
tensor([9.])
tensor([-7.])


In [190]:
x =  Variable(DoubleTensor([1]), requires_grad=True)

for i in range(5):
    y = x - torch.cos(x)
    y.backward()
    x = Variable(x.data - y.data/x.grad.data, requires_grad=True)

print(x.data) # tensor([0.7390851332151607], dtype=torch.float64)

tensor([0.7390851332151607], dtype=torch.float64)


In [191]:
x =  Variable(DoubleTensor([1]), requires_grad=True)
y = x - torch.cos(x)
y.backward(retain_graph=True)

for i in range(5):
    x.data = x.data - y.data/x.grad.data
    y.data = x.data - torch.cos(x.data)
    y.backward(retain_graph=True)

print(x.data) # tensor([0.7417889255761136], dtype=torch.float64)

tensor([0.7417889255761136], dtype=torch.float64)


In [192]:
def g(x): return x - math.cos(x)
def dg(x): return 1 + math.sin(x)

def solve(x):
    return x - g(x)/dg(x)

In [193]:
x = 1
for i in range(5):
    x = solve(x)
    print(x)

0.7503638678402439
0.7391128909113617
0.7390851333852839
0.7390851332151606
0.7390851332151607
