In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(2)

In [7]:
lin = nn.Linear(5, 3)
data = torch.randn(2, 5)
print(data)
print(lin(data))

tensor([[-0.8454,  0.9406, -2.1224,  0.0233,  0.4836],
        [ 1.2895,  0.8957, -0.2465,  1.9422, -0.3628]])
tensor([[-0.1001, -0.4700, -0.2762],
        [-0.0259, -0.6231,  1.0207]], grad_fn=<AddmmBackward>)


In [13]:
[p for p in lin.parameters()]

[Parameter containing:
 tensor([[-0.2782, -0.0843, -0.0661,  0.3985, -0.0281],
         [ 0.2425,  0.3275,  0.1992, -0.3889,  0.3352],
         [ 0.2949, -0.3206, -0.1595,  0.3044, -0.4347]], requires_grad=True),
 Parameter containing:
 tensor([-0.3920, -0.3031,  0.1394], requires_grad=True)]

In [14]:
print(lin.bias)

Parameter containing:
tensor([-0.3920, -0.3031,  0.1394], requires_grad=True)


In [21]:
torch.Tensor(3)

tensor([ 0.0000e+00,  4.6566e-10, -1.1075e-22])